"""empty message

Revision ID: a0e5d289b7f8
Revises: 
Create Date: 2025-04-09 01:26:38.613406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e5d289b7f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interfaces_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bandwidth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interfaces_tbl', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('bandwidth')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
